### ISSUE TITLE
feature request : make delta available in the dev release

### ISSUE THREAD

**Issue by djouallah** [duckdb/duckdb_delta#42]
for testing purpose it will be nice if delta extension is made available in the nightly build of duckdb

**Comment by samansmink** [comment]
@djouallah yea this is on my radar but to do so cleanly, we need to do some work upstream. Currently we have a bit of CI code duplication going on. The CI configuration in extension-ci-tools is actually not used to build the extensions for nightly builds of DuckDB. We are working towards unifying this for v1.1.0 so that DuckDB CI and extension CI are the same. Then we will also be able to just add the delta extension to DuckDB nightly builds.
